<?php

/**   
 * Implements hook_init().
 */ 
function spcontactform_init() {
  module_load_include("inc", "spcontactform", "spcontactform.form");
  module_load_include("inc", "spcontactform", "spcontactform.processing");
  module_load_include("inc", "spcontactform", "spcontactform.settings");
  module_load_include('inc', 'webform', 'includes/webform.submissions');
}   

/**
 * Implements hook_menu().
 */
function spcontactform_menu() {
  $items = array();

  $items['admin/config/sp/spcontactform'] = array(
    'title' => 'SP Contactform',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'spcontactform_overview',
    'file' => 'spcontactform.admin.inc',
    'access callback' => sprbs_access_check(),
  );

  $items['admin/config/sp/spcontactform/overview'] = array(
    'title' => 'Overzicht SP contactformulieren',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => '0',
  );

  $items['admin/config/sp/spcontactform/add'] = array(
    'title' => 'SP Contactform',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spcontactform_admin_form'),
    'file' => 'spcontactform.admin.inc',
    'access callback' => sprbs_access_check(),
  );

  $items['admin/config/sp/spcontactform/settings'] = array(
    'title' => 'Instellingen',
    'type' => MENU_LOCAL_TASK,
    'page callback'  => 'drupal_get_form',
    'page arguments' => array('spcontactform_settings_form'),
    'file' => 'spcontactform.admin.inc',
    'access callback' => sprbs_access_check(),
    'weight' => '1',
  );

  $items['admin/config/sp/spcontactform/delete/%'] = array(
    'title' => 'SP contactform delete',
    'page callback' => 'spcontactform_delete',
    'page arguments' => array(5),
    'access callback' => sprbs_access_check(),
    'type' => MENU_CALLBACK,
    'file' => 'spcontactform.admin.inc',
  );

  $items['spcontactform/group/autocomplete'] = array(
    'title' => 'SP contactform autocomplete',
    'page callback' => 'spcontactform_group_autocomplete',
    'access callback' => sprbs_access_check(),
    'type' => MENU_CALLBACK,
    'file' => 'spcontactform.admin.inc',
  );

  return $items;
}

/**
 *  Implements hook_node_delete.
 */
function spcontactform_node_delete($node) {
  // Delete spcontactform sync data if webform is deleted.
  if ($node->type === 'webform') {
    $sync_data = variable_get('spcontactform_sync_data', array());
    // Check if there is a spcontactform for this webform.
    if (isset($sync_data[$node->nid])) {
      unset($sync_data[$node->nid]);
      variable_set('spcontactform_sync_data', $sync_data);
      drupal_set_message('SP contactform nr. ' . $node->nid . ' attached to this form has been deleted.', 'warning');
    }
  }
}

/**
 *  Implements hook_webform_submission_insert.
 */
function spcontactform_webform_submission_insert($node, $submission) {
  $sync_data = variable_get('spcontactform_sync_data', FALSE);
  if (!empty($sync_data) && isset($sync_data[$node->nid])) {
    $sync_type = variable_get('spcontactform_sync_type'); 
    switch ($sync_type) {
    case 'direct':
      spcontactform_process_submission($submission);
      break;
    case 'cron':
      $postphoned_submission_syncs = variable_get('spcontactform_postphoned_submission_syncs', array());
      $postphoned_submission_syncs[$node->nid][$submission->sid] = $submission->sid;
      variable_set('spcontactform_postphoned_submission_syncs', $postphoned_submission_syncs);
    }
  }
}

/*
 * Implements hook_cron().
 *
 * Syncs not yet synced webform submissions.
 */
function spcontactform_cron() {
  $synced = 0;
  $max_cron_number = variable_get('spcontactform_cron_number', 0);
  $sync_data = variable_get('spcontactform_sync_data', FALSE);
  if (!empty($sync_data)) {
    $postphoned_submission_syncs = variable_get('spcontactform_postphoned_submission_syncs', array());
    foreach ($sync_data as $webform_id => $data) {
      if (!empty($postphoned_submission_syncs[$webform_id])) {
        foreach ($postphoned_submission_syncs[$webform_id] as $key => $submission_id) {
          $submission = webform_get_submission($webform_id, $submission_id);
          if (!empty($submission)) {
            // Break out of loop when max number of syncs is reached.
            if ($synced >= $max_cron_number) {
              break 2;
            }
            spcontactform_process_submission($submission);
            $synced ++;
            unset($postphoned_submission_syncs[$webform_id][$key]);
          }
        }
      }
    }
    variable_set('spcontactform_postphoned_submission_syncs', $postphoned_submission_syncs);
  }
}
